"Resource/UI/ControlPointCountdown.res"
{
	"CapCountdownLabel"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"CapCountdownLabel"
		"font"			"HudFontMediumBold"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"30"
		"tall"			"30"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"wrap"			"0"
		"labelText"		"%capturetime%"
		"textAlignment"		"center"
		"fgcolor"		"235 226 202 255"
		"bgcolor"		"235 226 202 255"
	}
	"CapCountdownLabelShadow"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"CapCountdownLabelShadow"
		"font"			"HudFontMediumBold"
		"xpos"			"-3"
		"ypos"			"-3"
		"zpos"			"1"
		"wide"			"30"
		"tall"			"30"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"wrap"			"0"
		"labelText"		"%capturetime%"
		"textAlignment"		"center"
		"fgcolor"		"TanDarker"

		"pin_to_sibling"	"CapCountdownLabel"
	}
}
